version: "3.7"

services:

  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assetManagement
    ports:
      - "6033:3306"
    networks:
      - asset
    volumes:
      - ./dbdata:/var/lib/mysql

  web-app:
    build: .
    links:
      - mysql
    ports:
      - "5000:5000"
    networks:
      - asset
    volumes:
      - ./dbdata:/var/lib/mysql

volumes:
  dbdata:

networks:
  asset:
