version: "3.7"

services:

  mysql:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: assetManagement
    ports:
      - "6033:3306"
    networks:
      - asset

  web-app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_DB: assetManagement
    networks:
      - asset

networks:
  asset:
    driver: bridge
